import { SchemeItem, NeedCategory, VerificationStatus } from '../types';

export interface StructuredScheme extends SchemeItem {
  id: number;
  name: string;
  shortName: string;
  details: string;
  benefits: string;
  eligibility: string;
  application: string;
  documents: string[];
  level: 'Central' | 'State';
  category: string;
  needCategory: NeedCategory;
  tags: string[];
  department: string;
  official_source: string;
  official_url: string;
  last_verified: string;
  last_updated: string;
  verification_status: VerificationStatus;
  incomeLimit: string;
  maxIncome?: number; // In INR per annum
  minAge?: number;
  maxAge?: number;
  targetGender?: 'All' | 'Male' | 'Female' | 'Transgender';
  requiredConditions?: string[];
  eligibleStates?: string[];
}

export const SCHEMES_DATABASE: StructuredScheme[] = [
  {
    id: 9901,
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    shortName: 'PM-KISAN',
    details: 'Direct income support of ₹6,000 per year in three equal installments of ₹2,000 every 4 months to all cultivable landholding farmer families.',
    benefits: 'Direct bank transfer of ₹6,000/year (₹2,000 every 4 months) directly credited to Aadhaar-linked bank accounts with zero intermediary fees.',
    eligibility: 'Cultivable landholding farmer families. Exclusions: Institutional landholders, income tax payees, sitting/former constitutional post holders.',
    application: 'Apply online at pmkisan.gov.in (Farmer Corner) or visit the nearest CSC / Gram Panchayat with Land Record and Aadhaar.',
    documents: ['Aadhaar Card', 'Land Record / Khasra-Khatauni', 'Bank Passbook', 'Active Mobile Number'],
    level: 'Central',
    category: 'Agriculture, Rural & Environment',
    needCategory: 'agriculture',
    tags: ['Farmers', 'Direct Benefit Transfer', 'Income Support', 'Agriculture'],
    department: 'Ministry of Agriculture and Farmers Welfare',
    official_source: 'National Informatics Centre / Ministry of Agriculture',
    official_url: 'https://pmkisan.gov.in',
    last_verified: '2026-08-15',
    last_updated: '2026-08-20',
    verification_status: 'recently_verified',
    incomeLimit: 'No strict income ceiling (Excludes Income Tax Payers)',
    maxIncome: 2500000,
    minAge: 18,
    maxAge: 100,
    targetGender: 'All',
    requiredConditions: ['Farmer']
  },
  {
    id: 9902,
    name: 'Ayushman Bharat - PM Jan Arogya Yojana (AB-PMJAY)',
    shortName: 'PM-JAY',
    details: 'World largest government health assurance scheme offering health cover of up to ₹5,00,000 per family per year for secondary and tertiary care hospitalization.',
    benefits: 'Cashless and paperless hospitalization coverage up to ₹5 Lakh/family/year covering 1,949 treatments, surgeries, diagnostic tests, and post-discharge medicines.',
    eligibility: 'Families identified based on SECC 2011 deprivation criteria or having a Ration Card / Antyodaya Anna Yojana. Expanded to all senior citizens aged 70+ regardless of income.',
    application: 'Check eligibility at mera.pmjay.gov.in using Aadhaar/Ration Card. Visit any impaneled government or private hospital helpdesk with Aadhaar.',
    documents: ['Aadhaar Card', 'Ration Card / Family ID', 'Income Certificate / BPL Card', 'Active Mobile Number'],
    level: 'Central',
    category: 'Health & Wellness',
    needCategory: 'healthcare',
    tags: ['Healthcare', 'Hospitalization', 'Cashless Health Cover', 'Medical Aid'],
    department: 'National Health Authority (NHA)',
    official_source: 'National Health Authority, Ministry of Health and Family Welfare',
    official_url: 'https://mera.pmjay.gov.in',
    last_verified: '2026-08-28',
    last_updated: '2026-08-29',
    verification_status: 'recently_verified',
    incomeLimit: '₹3,00,000 per year (or Senior Citizen 70+)',
    maxIncome: 300000,
    minAge: 0,
    maxAge: 100,
    targetGender: 'All',
    requiredConditions: ['Low Income / BPL', 'Healthcare Need']
  },
  {
    id: 9903,
    name: 'Pradhan Mantri Awas Yojana - Gramin & Urban (PMAY)',
    shortName: 'PMAY',
    details: 'Flagship housing scheme aimed at providing pucca houses with basic civic amenities (water, electricity, sanitation) to all eligible homeless and kutcha house residents.',
    benefits: 'Direct financial subsidy of ₹1.20 Lakh to ₹1.30 Lakh in rural areas or interest subsidy of up to ₹2.67 Lakh under CLSS in urban areas.',
    eligibility: 'Homeless families or families living in zero/one/two room kutcha houses with kutcha roof. Female head of family is preferred co-owner.',
    application: 'Rural: Apply via Gram Panchayat or AwaasApp. Urban: Apply via pmaymis.gov.in or Common Service Center.',
    documents: ['Aadhaar Card', 'Job Card / MGNREGA Card', 'Bank Passbook', 'Land / Homestead Document', 'Income Certificate'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'housing',
    tags: ['Housing', 'Pucca House', 'Rural Development', 'Urban Housing'],
    department: 'Ministry of Housing and Urban Affairs & Ministry of Rural Development',
    official_source: 'Ministry of Housing and Urban Affairs',
    official_url: 'https://pmaymis.gov.in',
    last_verified: '2026-08-10',
    last_updated: '2026-08-18',
    verification_status: 'recently_verified',
    incomeLimit: '₹3,00,000 for EWS, ₹6,00,000 for LIG',
    maxIncome: 300000,
    minAge: 18,
    maxAge: 85,
    targetGender: 'All',
    requiredConditions: ['Homeless / Kutcha House']
  },
  {
    id: 9904,
    name: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    shortName: 'NMMSS Scholarship',
    details: 'Central scholarship providing financial assistance of ₹12,000 per annum (₹1,000/month) to meritorious students from economically weaker sections to arrest dropouts at class VIII.',
    benefits: '₹12,000 per annum credited directly to student bank account from class IX to XII through National Scholarship Portal.',
    eligibility: 'Students studying in Government, Local Body, or Government-aided schools with at least 55% marks in Class VII. Parental annual income must not exceed ₹3,50,000.',
    application: 'Apply online through National Scholarship Portal (scholarships.gov.in) after qualifying the state selection test.',
    documents: ['Aadhaar Card', 'Student ID Card', 'Class VII/VIII Marksheet', 'Income Certificate', 'Bank Account in Student Name'],
    level: 'Central',
    category: 'Education & Learning',
    needCategory: 'education',
    tags: ['Scholarship', 'School Education', 'Financial Assistance', 'Students'],
    department: 'Department of School Education & Literacy, Ministry of Education',
    official_source: 'National Scholarship Portal (NSP)',
    official_url: 'https://scholarships.gov.in',
    last_verified: '2026-08-25',
    last_updated: '2026-08-27',
    verification_status: 'recently_verified',
    incomeLimit: '₹3,50,000 per annum',
    maxIncome: 350000,
    minAge: 12,
    maxAge: 20,
    targetGender: 'All',
    requiredConditions: ['Student']
  },
  {
    id: 9905,
    name: 'Central Sector Scheme of Scholarships for College and University Students',
    shortName: 'PM-USP Higher Education Scholarship',
    details: 'Financial assistance of ₹12,000 to ₹20,000 per year for meritorious students from low-income families pursuing higher college or university education.',
    benefits: '₹12,000/year for undergraduate courses (first 3 years) and ₹20,000/year for postgraduate courses credited directly via DBT.',
    eligibility: 'Students above 80th percentile in Class 12 board exams, enrolled in regular recognized degree college. Family annual income must be below ₹4,50,000.',
    application: 'Apply on scholarships.gov.in during the open academic cycle. Verification done by the respective college/university institute nodal officer.',
    documents: ['Aadhaar Card', 'Class 12 Marksheet', 'College Admission Proof / Fee Receipt', 'Income Certificate', 'Student Bank Passbook'],
    level: 'Central',
    category: 'Education & Learning',
    needCategory: 'education',
    tags: ['College Scholarship', 'University Grant', 'Higher Education', 'Financial Aid'],
    department: 'Department of Higher Education, Ministry of Education',
    official_source: 'Ministry of Education & National Scholarship Portal',
    official_url: 'https://scholarships.gov.in',
    last_verified: '2026-08-30',
    last_updated: '2026-08-31',
    verification_status: 'recently_verified',
    incomeLimit: '₹4,50,000 per annum',
    maxIncome: 450000,
    minAge: 17,
    maxAge: 28,
    targetGender: 'All',
    requiredConditions: ['Student']
  },
  {
    id: 9906,
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
    shortName: 'PMKVY Skill Training',
    details: 'Flagship skill certification scheme offering free industry-relevant technical and vocational training, stipend, and placement assistance to unemployed youth and dropouts.',
    benefits: '100% free technical skill training, government-recognized NSDC certification, ₹8,000 reward bonus, and placement support with top employers.',
    eligibility: 'Indian youth aged 15 to 45 who are unemployed, school/college dropouts, or seeking formal skill upskilling and certification.',
    application: 'Register online at skillindia.gov.in or visit any nearest PMKK (Pradhan Mantri Kaushal Kendra) training center.',
    documents: ['Aadhaar Card', 'Educational Certificate / Highest Qualification Marksheet', 'Bank Account Passbook', '2 Passport Size Photos'],
    level: 'Central',
    category: 'Skills & Employment',
    needCategory: 'skill_development',
    tags: ['Skill Training', 'Vocational Course', 'Employment', 'Certification', 'Youth'],
    department: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
    official_source: 'National Skill Development Corporation (NSDC)',
    official_url: 'https://www.skillindia.gov.in',
    last_verified: '2026-08-22',
    last_updated: '2026-08-25',
    verification_status: 'recently_verified',
    incomeLimit: 'No income limit',
    maxIncome: 5000000,
    minAge: 15,
    maxAge: 45,
    targetGender: 'All',
    requiredConditions: ['Unemployed', 'Seeking Skills']
  },
  {
    id: 9907,
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    shortName: 'Mudra Business Loan',
    details: 'Collateral-free institutional credit up to ₹20 Lakh to micro and small non-corporate non-farm enterprises under Shishu, Kishore, and Tarun categories.',
    benefits: 'Collateral-free micro enterprise loan: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 Lakh), Tarun (₹5 Lakh to ₹10 Lakh), and Tarun Plus (up to ₹20 Lakh).',
    eligibility: 'Non-farm micro or small business owners, artisans, shopkeepers, service providers, food processors, and women entrepreneurs.',
    application: 'Apply online via Udyamimitra portal (udyamimitra.in) or visit any commercial bank, RRB, or MFI with business plan.',
    documents: ['Aadhaar Card', 'PAN Card', 'Business Address Proof / Udyam Registration', 'Bank Statement (Last 6 Months)', 'Quotations of Machinery / Equipment'],
    level: 'Central',
    category: 'Business & Entrepreneurship',
    needCategory: 'entrepreneurship',
    tags: ['Micro Loan', 'Self-Employment', 'Startup Support', 'Collateral Free', 'MSME'],
    department: 'Department of Financial Services, Ministry of Finance',
    official_source: 'Ministry of Finance & SIDBI',
    official_url: 'https://www.mudra.org.in',
    last_verified: '2026-08-18',
    last_updated: '2026-08-21',
    verification_status: 'recently_verified',
    incomeLimit: 'No income cap (evaluated on business viability)',
    maxIncome: 10000000,
    minAge: 18,
    maxAge: 70,
    targetGender: 'All',
    requiredConditions: ['Entrepreneur / Self-Employed']
  },
  {
    id: 9908,
    name: 'National Rural Employment Guarantee Act (MGNREGA)',
    shortName: 'MGNREGA Job Guarantee',
    details: 'Legal entitlement guaranteeing at least 100 days of wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.',
    benefits: 'Guaranteed wage employment with wages directly credited to bank account within 15 days; unemployment allowance if work is not provided within 15 days of demand.',
    eligibility: 'Adult members of any rural household residing in Gram Panchayat area willing to do unskilled manual work.',
    application: 'Apply for Job Card at local Gram Panchayat office. Submit written application or demand for work.',
    documents: ['Aadhaar Card', 'Ration Card', 'Bank Passbook', 'Passport size photographs'],
    level: 'Central',
    category: 'Skills & Employment',
    needCategory: 'employment',
    tags: ['Rural Employment', 'Wage Guarantee', 'Livelihood', 'Job Card'],
    department: 'Ministry of Rural Development',
    official_source: 'Ministry of Rural Development',
    official_url: 'https://nrega.nic.in',
    last_verified: '2026-08-12',
    last_updated: '2026-08-16',
    verification_status: 'recently_verified',
    incomeLimit: 'Rural household with willingness to do manual wage work',
    maxIncome: 250000,
    minAge: 18,
    maxAge: 70,
    targetGender: 'All',
    requiredConditions: ['Unemployed', 'Rural Resident']
  },
  {
    id: 9909,
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    shortName: 'PMMVY Maternity Benefit',
    details: 'Conditional cash transfer maternity benefit scheme of ₹5,000 for the first child and ₹6,000 for the second child (if girl) to pregnant women and lactating mothers.',
    benefits: 'Cash incentive of up to ₹6,000 transferred directly via DBT to compensate wage loss and encourage institutional deliveries.',
    eligibility: 'Pregnant women and lactating mothers aged 19 years or above from socially/economically disadvantaged sections. (Excludes regular Govt employees).',
    application: 'Register at nearest Anganwadi Centre (AWC) or apply online at pmmvy.wcd.gov.in using MCP card and Aadhaar.',
    documents: ['Aadhaar Card of Mother & Husband', 'Mother-Child Protection (MCP) Card', 'Bank Account in Mother Name', 'Income / BPL Proof'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'women_welfare',
    tags: ['Maternity Benefit', 'Women Welfare', 'Cash Transfer', 'Healthcare'],
    department: 'Ministry of Women and Child Development',
    official_source: 'Ministry of Women and Child Development',
    official_url: 'https://pmmvy.wcd.gov.in',
    last_verified: '2026-08-19',
    last_updated: '2026-08-20',
    verification_status: 'recently_verified',
    incomeLimit: '₹8,00,000 per annum (EWS/BPL/SC/ST/E-Shram holders priority)',
    maxIncome: 800000,
    minAge: 19,
    maxAge: 45,
    targetGender: 'Female',
    requiredConditions: ['Pregnant / Lactating Mother']
  },
  {
    id: 9910,
    name: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    shortName: 'IGNOAPS Senior Pension',
    details: 'Monthly social security financial pension for elderly citizens living below the poverty line to ensure dignity and basic sustenance in old age.',
    benefits: 'Monthly direct cash pension of ₹200 to ₹500 (with state co-contribution totaling ₹1,000 to ₹2,500/month depending on state) directly credited to bank account.',
    eligibility: 'Citizens aged 60 years and above belonging to a household living Below the Poverty Line (BPL) as per central/state guidelines.',
    application: 'Apply online via NSAP portal (nsap.nic.in) or offline via Block Development Office / Taluk Social Welfare Office.',
    documents: ['Aadhaar Card', 'Age Proof (Birth Certificate/Voter ID)', 'BPL Ration Card / Income Certificate', 'Bank Passbook'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'senior_citizen_welfare',
    tags: ['Old Age Pension', 'Senior Citizen', 'Social Security', 'BPL Support'],
    department: 'National Social Assistance Programme (NSAP), Ministry of Rural Development',
    official_source: 'Ministry of Rural Development (NSAP)',
    official_url: 'https://nsap.nic.in',
    last_verified: '2026-08-14',
    last_updated: '2026-08-15',
    verification_status: 'recently_verified',
    incomeLimit: 'BPL household criteria / Below ₹1,20,000 per annum',
    maxIncome: 120000,
    minAge: 60,
    maxAge: 110,
    targetGender: 'All',
    requiredConditions: ['Senior Citizen', 'BPL']
  },
  {
    id: 9911,
    name: 'Unique Disability ID (UDID) & Divyangjan Welfare Benefits',
    shortName: 'UDID Disability Support',
    details: 'Single centralized identity card and comprehensive welfare program providing assistive aids, transport concessions, scholarships, and pension for persons with disabilities.',
    benefits: 'Free assistive motorized tricycles, hearing aids, braille kits, national transport discounts (75% on rail), and monthly disability pensions.',
    eligibility: 'Persons with certified benchmark disability (40% or more) as evaluated by a designated government medical board.',
    application: 'Register online on the Swavlamban portal (swavlambancard.gov.in) with disability certificate and Aadhaar.',
    documents: ['Aadhaar Card', 'Disability Medical Certificate', 'Recent Passport Size Color Photo', 'Address Proof', 'Bank Passbook'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'disability_support',
    tags: ['Disability Card', 'Divyangjan', 'Assistive Devices', 'Social Security'],
    department: 'Department of Empowerment of Persons with Disabilities, MSJE',
    official_source: 'Department of Empowerment of Persons with Disabilities',
    official_url: 'https://www.swavlambancard.gov.in',
    last_verified: '2026-08-20',
    last_updated: '2026-08-22',
    verification_status: 'recently_verified',
    incomeLimit: '₹2,50,000 for free aid distribution',
    maxIncome: 250000,
    minAge: 0,
    maxAge: 100,
    targetGender: 'All',
    requiredConditions: ['Differently Abled']
  },
  {
    id: 9912,
    name: 'Atal Pension Yojana (APY)',
    shortName: 'Atal Pension Yojana',
    details: 'Government-backed guaranteed minimum monthly pension scheme for workers in the unorganized sector to build retirement income.',
    benefits: 'Guaranteed minimum monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 per month starting at age 60 based on modest monthly contributions.',
    eligibility: 'All Indian citizens aged 18 to 40 having a savings bank account. Must not be an income taxpayer.',
    application: 'Apply online through Net Banking / mobile banking or visit any bank branch where savings account is held.',
    documents: ['Aadhaar Card', 'Savings Bank Account Number', 'Active Mobile Number'],
    level: 'Central',
    category: 'Banking, Financial Services & Insurance',
    needCategory: 'social_security',
    tags: ['Retirement Pension', 'Guaranteed Monthly Income', 'Unorganized Workers', 'Social Security'],
    department: 'Pension Fund Regulatory and Development Authority (PFRDA)',
    official_source: 'PFRDA / Ministry of Finance',
    official_url: 'https://www.npscra.nsdl.co.in',
    last_verified: '2026-08-16',
    last_updated: '2026-08-19',
    verification_status: 'recently_verified',
    incomeLimit: 'Non-income taxpayer at time of enrollment',
    maxIncome: 500000,
    minAge: 18,
    maxAge: 40,
    targetGender: 'All',
    requiredConditions: ['Unorganized Worker / Self-Employed']
  },
  {
    id: 9913,
    name: 'Stand-Up India Scheme for Women & SC/ST Entrepreneurs',
    shortName: 'Stand-Up India',
    details: 'Facilitates bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST borrower and one woman borrower per bank branch for setting up greenfield enterprises.',
    benefits: 'Composite bank loan from ₹10 Lakh to ₹1 Crore with credit guarantee, handholding support, margin money subsidy, and working capital credit.',
    eligibility: 'SC/ST and/or Woman entrepreneurs aged 18+ establishing a new greenfield enterprise in manufacturing, services, agri-allied, or trading sector.',
    application: 'Register online at standupmitra.in or contact the lead district bank manager.',
    documents: ['Aadhaar Card', 'PAN Card', 'Caste Certificate (if SC/ST)', 'Project Report & Business Feasibility Plan', 'Bank Statements'],
    level: 'Central',
    category: 'Business & Entrepreneurship',
    needCategory: 'entrepreneurship',
    tags: ['Women Entrepreneur', 'SC/ST Enterprise', 'High Value Business Loan', 'Manufacturing'],
    department: 'Department of Financial Services, Ministry of Finance',
    official_source: 'SIDBI / Ministry of Finance',
    official_url: 'https://www.standupmitra.in',
    last_verified: '2026-07-25',
    last_updated: '2026-08-01',
    verification_status: 'verification_due',
    incomeLimit: 'No personal income limit (assessed on project viability)',
    maxIncome: 20000000,
    minAge: 18,
    maxAge: 70,
    targetGender: 'All',
    requiredConditions: ['Woman / SC / ST', 'Entrepreneur']
  },
  {
    id: 9914,
    name: 'PM Vishwakarma Scheme for Traditional Artisans',
    shortName: 'PM Vishwakarma',
    details: 'Holistic support to traditional artisans and craftspeople working with hands and tools across 18 family trades with recognition, skill training, toolkit grant, and low-interest credit.',
    benefits: 'PM Vishwakarma Certificate & ID Card, free 5-7 days basic skill training with ₹500/day stipend, ₹15,000 modern toolkit incentive, and collateral-free enterprise loan up to ₹3 Lakh at 5% interest.',
    eligibility: 'Artisans or craftspeople engaged in one of 18 trades (carpenter, blacksmith, goldsmith, potter, sculptor, cobbler, tailor, mason, etc.) on self-employment basis. Min age 18.',
    application: 'Apply online via CSC on pmvishwakarma.gov.in. Verification involves Gram Panchayat / Urban Local Body scrutiny.',
    documents: ['Aadhaar Card', 'Bank Passbook', 'Ration Card', 'Active Mobile Number'],
    level: 'Central',
    category: 'Skills & Employment',
    needCategory: 'skill_development',
    tags: ['Traditional Artisans', 'ToolKit Grant', 'Low Interest Loan', 'Skill Training', 'Handicraft'],
    department: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    official_source: 'Ministry of MSME',
    official_url: 'https://pmvishwakarma.gov.in',
    last_verified: '2026-08-26',
    last_updated: '2026-08-27',
    verification_status: 'recently_verified',
    incomeLimit: 'No explicit income limit (family trade verification applies)',
    maxIncome: 600000,
    minAge: 18,
    maxAge: 75,
    targetGender: 'All',
    requiredConditions: ['Artisan / Craftsperson']
  },
  {
    id: 9915,
    name: 'Sukanya Samriddhi Yojana (SSY) for Girl Child',
    shortName: 'Sukanya Samriddhi Yojana',
    details: 'Government-backed high-interest savings scheme designed exclusively for parents of girl children to build dedicated funds for higher education and marriage.',
    benefits: 'Attractive government interest rate (currently 8.2% p.a.), Section 80C tax exemption on deposits, interest, and maturity, with 100% sovereign safety.',
    eligibility: 'Parents or legal guardians of a girl child from birth up to 10 years of age. Max 2 accounts per family (or 3 in case of twins).',
    application: 'Open account at any Post Office or authorized commercial bank branch with girl child birth certificate and parent KYC.',
    documents: ['Girl Child Birth Certificate', 'Parent/Guardian Aadhaar & PAN Card', 'Address Proof', 'Passport size photographs'],
    level: 'Central',
    category: 'Banking, Financial Services & Insurance',
    needCategory: 'child_welfare',
    tags: ['Girl Child', 'Education Fund', 'High Interest Savings', 'Tax Free'],
    department: 'Department of Economic Affairs, Ministry of Finance',
    official_source: 'India Post / Ministry of Finance',
    official_url: 'https://www.indiapost.gov.in',
    last_verified: '2026-08-29',
    last_updated: '2026-08-30',
    verification_status: 'recently_verified',
    incomeLimit: 'Open to all income groups',
    maxIncome: 10000000,
    minAge: 0,
    maxAge: 10,
    targetGender: 'Female',
    requiredConditions: ['Girl Child < 10 Years']
  },
  {
    id: 9916,
    name: 'National Social Assistance Programme - Widow Pension (IGNWPS)',
    shortName: 'IGNWPS Widow Pension',
    details: 'Monthly direct financial pension assistance for widows living below the poverty line to support their livelihood and family wellbeing.',
    benefits: 'Monthly direct cash pension of ₹300 (central share) plus state matching grant (totaling ₹1,000 - ₹2,000/month) transferred directly to bank account.',
    eligibility: 'Widows aged between 40 and 59 years belonging to a household below the poverty line (BPL). Above 60, automatically transitions to IGNOAPS.',
    application: 'Apply online via NSAP portal or submit form at Block Development Office or Municipal Corporation office.',
    documents: ['Aadhaar Card', 'Husband Death Certificate', 'BPL Ration Card / Income Certificate', 'Bank Account Passbook'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'women_welfare',
    tags: ['Widow Pension', 'Women Welfare', 'Social Security', 'BPL Assistance'],
    department: 'Ministry of Rural Development',
    official_source: 'National Social Assistance Programme (NSAP)',
    official_url: 'https://nsap.nic.in',
    last_verified: '2026-08-11',
    last_updated: '2026-08-14',
    verification_status: 'recently_verified',
    incomeLimit: 'BPL household threshold / Under ₹1,50,000 per annum',
    maxIncome: 150000,
    minAge: 40,
    maxAge: 59,
    targetGender: 'Female',
    requiredConditions: ['Widow', 'BPL']
  },
  {
    id: 9917,
    name: 'PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar Subsidy)',
    shortName: 'PM Surya Ghar',
    details: 'National rooftop solar program providing free electricity up to 300 units every month for 1 Crore households along with massive capital subsidies directly into bank accounts.',
    benefits: 'Direct DBT subsidy of ₹30,000 for 1 kW system, ₹60,000 for 2 kW system, and ₹78,000 for 3 kW+ system. Concessional collateral-free bank loans at ~7% interest for remaining cost.',
    eligibility: 'Indian citizen household owning a suitable roof with an active domestic electricity connection and consumer number.',
    application: 'Apply online at pmsuryaghar.gov.in with electricity consumer number, select registered vendor for rooftop installation, inspect net-metering, and receive DBT subsidy within 30 days.',
    documents: ['Aadhaar Card', 'Recent Electricity Bill (<2 months)', 'Roof Ownership Proof / House Tax Receipt', 'Bank Passbook / Cancelled Cheque'],
    level: 'Central',
    category: 'Infrastructure, Energy & Housing',
    needCategory: 'housing',
    tags: ['Solar Subsidy', 'Free Electricity', 'Rooftop Solar', 'Green Energy', 'DBT'],
    department: 'Ministry of New and Renewable Energy (MNRE)',
    official_source: 'National Portal for Rooftop Solar / MNRE',
    official_url: 'https://pmsuryaghar.gov.in',
    last_verified: '2026-08-28',
    last_updated: '2026-08-30',
    verification_status: 'recently_verified',
    incomeLimit: 'No income restriction (Open to all domestic electricity consumers)',
    maxIncome: 5000000,
    minAge: 18,
    maxAge: 99,
    targetGender: 'All',
    requiredConditions: ['Electricity Consumer']
  },
  {
    id: 9918,
    name: 'National Apprenticeship Promotion Scheme (NAPS 2.0)',
    shortName: 'NAPS 2.0 Apprenticeship',
    details: 'Flagship skill empowerment program bridging youth education and industry employment through formal apprenticeships with direct government-funded stipend support.',
    benefits: 'Government co-funds 25% of prescribed monthly stipend up to ₹1,500/month directly to apprentice bank account via DBT. Includes industry certification upon completion.',
    eligibility: 'Youth aged 14 to 35 years who have completed 5th, 8th, 10th, 12th, ITI, Diploma, or Graduation.',
    application: 'Register as candidate on apprenticeshipindia.gov.in, search apprentice opportunities across 1,00,000+ establishments, and apply online.',
    documents: ['Aadhaar Card', 'Educational Marksheets (10th/12th/ITI/Degree)', 'Bank Passbook copy for DBT', 'Passport size photograph'],
    level: 'Central',
    category: 'Skills & Employment',
    needCategory: 'skill_development',
    tags: ['Apprenticeship', 'Stipend Support', 'Youth Jobs', 'Skill India', 'Vocational Training'],
    department: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
    official_source: 'National Skill Development Corporation (NSDC)',
    official_url: 'https://www.apprenticeshipindia.gov.in',
    last_verified: '2026-08-25',
    last_updated: '2026-08-28',
    verification_status: 'recently_verified',
    incomeLimit: 'No income ceiling',
    maxIncome: 10000000,
    minAge: 14,
    maxAge: 35,
    targetGender: 'All',
    requiredConditions: ['Student / Unemployed Youth']
  },
  {
    id: 9919,
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY 2.0)',
    shortName: 'PMMVY Matru Vandana',
    details: 'Direct conditional cash transfer maternity benefit scheme for pregnant women and lactating mothers to provide wage compensation and improved maternal nutrition.',
    benefits: '₹5,000 in two installments (₹3,000 upon early pregnancy registration + ANC, ₹2,000 upon child birth and primary vaccination) for first child; and ₹6,000 incentive in single installment if second child is a girl.',
    eligibility: 'Pregnant women and lactating mothers aged 19+ belonging to socially or economically disadvantaged categories (income < ₹8 Lakh, BPL/EWS, e-Shram registered, or SC/ST).',
    application: 'Apply online at pmmvy.wcd.gov.in or submit form at Anganwadi Centre / approved Government Health Facility within 270 days of pregnancy.',
    documents: ['Mother & Father Aadhaar Cards', 'MCP Card (Mother and Child Protection Card)', 'Mother Bank Account Passbook (Aadhaar-linked)', 'Child Birth Certificate (for 2nd installment)'],
    level: 'Central',
    category: 'Women & Child Welfare',
    needCategory: 'women_welfare',
    tags: ['Maternity Benefit', 'Cash Transfer', 'Pregnant Women', 'Child Health', 'Nutrition'],
    department: 'Ministry of Women and Child Development (MWCD)',
    official_source: 'PMMVY Portal / Ministry of Women & Child Development',
    official_url: 'https://pmmvy.wcd.gov.in',
    last_verified: '2026-08-20',
    last_updated: '2026-08-22',
    verification_status: 'recently_verified',
    incomeLimit: 'Family income under ₹8,00,000 / BPL / EWS / e-Shram cardholder',
    maxIncome: 800000,
    minAge: 19,
    maxAge: 45,
    targetGender: 'Female',
    requiredConditions: ['Pregnant / Lactating Mother']
  },
  {
    id: 9920,
    name: 'Kisan Credit Card (KCC) Scheme',
    shortName: 'Kisan Credit Card (KCC)',
    details: 'Institutional credit mechanism providing farmers, animal husbandry rearers, and fisheries workers timely short-term credit for cultivation, farm maintenance, and post-harvest expenses.',
    benefits: 'Concessional crop loans up to ₹3 Lakh at an effective interest rate of only 4% per annum (7% base rate minus 3% prompt repayment incentive) with collateral-free limit up to ₹1.6 Lakh.',
    eligibility: 'All farmers - individual/joint land cultivators, tenant farmers, oral lessees, sharecroppers, and SHG farmer groups.',
    application: 'Download simplified one-page KCC application from agricoop.nic.in or pmkisan.gov.in and submit at your local commercial bank / RRB / Cooperative bank branch.',
    documents: ['Aadhaar Card', 'Land Revenue Records (7/12 / Khasra-Khatauni)', 'Cropping Pattern Declaration', 'Passport photograph'],
    level: 'Central',
    category: 'Agriculture, Rural & Environment',
    needCategory: 'agriculture',
    tags: ['Kisan Credit Card', 'Crop Loan', 'Low Interest Credit', 'Agriculture', 'Farmers'],
    department: 'Department of Agriculture & Farmers Welfare, Ministry of Agriculture',
    official_source: 'NABARD / Ministry of Agriculture',
    official_url: 'https://agricoop.nic.in',
    last_verified: '2026-08-18',
    last_updated: '2026-08-20',
    verification_status: 'recently_verified',
    incomeLimit: 'Assessed on cultivable land area and crop scale',
    maxIncome: 10000000,
    minAge: 18,
    maxAge: 75,
    targetGender: 'All',
    requiredConditions: ['Farmer']
  },
  {
    id: 9921,
    name: 'One Nation One Ration Card (NFSA Food Security)',
    shortName: 'ONORC / NFSA Foodgrain',
    details: 'National portability enabling migrant workers and NFSA beneficiaries to claim their entitled subsidized foodgrains from any Fair Price Shop (FPS) anywhere in India using biometric e-PoS authentication.',
    benefits: 'Free / highly subsidized foodgrains (5 kg per person per month under Priority Households and 35 kg per family under Antyodaya Anna Yojana) under Pradhan Mantri Garib Kalyan Anna Yojana (PMGKAY).',
    eligibility: 'Households holding NFSA Ration Card (Antyodaya or Priority Household category) with seeded Aadhaar.',
    application: 'Check entitlement on Mera Ration mobile app or visit any nearby Fair Price Shop with Aadhaar and Ration card number.',
    documents: ['Aadhaar Card of beneficiary', 'Active Ration Card Number'],
    level: 'Central',
    category: 'Social Welfare & Food Security',
    needCategory: 'social_security',
    tags: ['Food Security', 'Ration Card', 'Free Foodgrains', 'Migrant Portability', 'NFSA'],
    department: 'Department of Food and Public Distribution',
    official_source: 'National Food Security Portal',
    official_url: 'https://nfsa.gov.in',
    last_verified: '2026-08-27',
    last_updated: '2026-08-29',
    verification_status: 'recently_verified',
    incomeLimit: 'BPL / Antyodaya / Priority Household criteria',
    maxIncome: 200000,
    minAge: 0,
    maxAge: 100,
    targetGender: 'All',
    requiredConditions: ['BPL / Ration Card Holder']
  },
  {
    id: 9922,
    name: 'Pradhan Mantri Ujjwala Yojana 2.0 (PMUY)',
    shortName: 'PM Ujjwala 2.0',
    details: 'Clean cooking fuel access scheme providing deposit-free LPG connections along with targeted cylinder subsidies to women from poor and underprivileged households.',
    benefits: 'Deposit-free LPG connection (cylinder security + regulator), free first refill, free stove (hotplate), plus targeted government subsidy of ₹300 per 14.2 kg cylinder for up to 12 refills/year.',
    eligibility: 'Adult woman (18+) belonging to SC, ST, Pradhan Mantri Awas Yojana (PMAY), Antyodaya Anna Yojana (AAY), Most Backward Classes, or 14-point declaration poor households. No other LPG connection in family.',
    application: 'Apply online at pmuy.gov.in or submit Form 1 at any local LPG distributor (Indane, Bharatgas, HP Gas).',
    documents: ['Woman Aadhaar Card', 'Ration Card / Family Composition Proof', 'Aadhaar of all adult family members', 'Bank Account Passbook (Aadhaar linked)'],
    level: 'Central',
    category: 'Social Welfare & Housing',
    needCategory: 'women_welfare',
    tags: ['LPG Connection', 'Free Gas Cylinder', 'Women Health', 'Clean Fuel', 'Subsidy'],
    department: 'Ministry of Petroleum and Natural Gas (MoPNG)',
    official_source: 'PMUY Portal / MoPNG',
    official_url: 'https://pmuy.gov.in',
    last_verified: '2026-08-16',
    last_updated: '2026-08-19',
    verification_status: 'recently_verified',
    incomeLimit: 'Poor / Low Income Household without existing LPG',
    maxIncome: 250000,
    minAge: 18,
    maxAge: 80,
    targetGender: 'Female',
    requiredConditions: ['Low Income Household', 'Woman']
  }
];
